// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZKsEMSA-7Ibqa7GpEPRTbFAVo0keVd6w',
    appId: '1:810269009285:web:6c8d328f4d1783c02a50ec',
    messagingSenderId: '810269009285',
    projectId: 'one-sync-c5f90',
    authDomain: 'one-sync-c5f90.firebaseapp.com',
    storageBucket: 'one-sync-c5f90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxZFyQ2nksyjY_4lEdXbmYPdeYnlS_APw',
    appId: '1:810269009285:android:7ced5927415a2f882a50ec',
    messagingSenderId: '810269009285',
    projectId: 'one-sync-c5f90',
    storageBucket: 'one-sync-c5f90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL3d0Be5EjhqgdlCa6z-hoV-rU0FhzEg8',
    appId: '1:810269009285:ios:27dec286ee16533e2a50ec',
    messagingSenderId: '810269009285',
    projectId: 'one-sync-c5f90',
    storageBucket: 'one-sync-c5f90.firebasestorage.app',
    iosBundleId: 'com.example.onesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL3d0Be5EjhqgdlCa6z-hoV-rU0FhzEg8',
    appId: '1:810269009285:ios:27dec286ee16533e2a50ec',
    messagingSenderId: '810269009285',
    projectId: 'one-sync-c5f90',
    storageBucket: 'one-sync-c5f90.firebasestorage.app',
    iosBundleId: 'com.example.onesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZKsEMSA-7Ibqa7GpEPRTbFAVo0keVd6w',
    appId: '1:810269009285:web:87f93ccf2f2264ff2a50ec',
    messagingSenderId: '810269009285',
    projectId: 'one-sync-c5f90',
    authDomain: 'one-sync-c5f90.firebaseapp.com',
    storageBucket: 'one-sync-c5f90.firebasestorage.app',
  );
}
